spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update  # 이미 Workbench에서 만든 DB라면 'none' 또는 'validate'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
